<?php

namespace ContainerROQFWR2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0Vaziks.App\Entity\Projet' shared service.
     *
     * @return \App\Entity\Projet
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0Vaziks": it references class "App\\Entity\\Projet" but no such service exists.');
    }
}
