app_back:
    path: /admin
    controller: App\Controller\BackController::index

app_front:
    path: /
    controller: App\Controller\FrontController::index

#HomePage
home_one_get:
    path: /home
    controller: App\Controller\AcceuilController::getHomeOne
    methods: GET

home_one_update:
    path: /home/homeOne/update
    controller: App\Controller\AcceuilController::updateHomeOne
    methods: [PUT,PATCH]

home_two_get:
    path: /home/homeTwo
    controller: App\Controller\AcceuilController::getHomeTwo
    methods: GET

home_two_update:
    path: /api/home/homeTwo/update
    controller: App\Controller\AcceuilController::updateHomeTwo
    methods: [PUT,PATCH]

#Testimonial
client_testimonial_get:
    path: /testimonial/client
    controller: App\Controller\TestimonialController::getAll
    methods: GET
client_testimonial_get_by_id:
    path: /testimonial/client/{id}
    controller: App\Controller\TestimonialController::getTestimonialById
    methods: GET
create_testimonial_client:
    path: /testimonial/client/create
    controller: App\Controller\TestimonialController::createClientTestimonial
    methods: POST
update_testimonial_client:
    path: /testimonial/client/update/{id}
    controller: App\Controller\TestimonialController::updateTestimonial
    methods: [PUT,PATCH]
client_testimonial_delete:
    path: /testimonial/client/delete/{id}
    controller: App\Controller\TestimonialController::deleteById
    methods: DELETE 
#Team Testimonial
team_testimonial_get:
    path: /testimonial/team
    controller: App\Controller\TestimonialTeamController::getAll
    methods: GET
team_testimonial_get_by_id:
    path: /testimonial/team/{id}
    controller: App\Controller\TestimonialTeamController::getTeamTestimonialById
    methods: GET
create_testimonial_team:
    path: /testimonial/team/create
    controller: App\Controller\TestimonialTeamController::createTeamTestimonial
    methods: POST
update_testimonial_team:
    path: /testimonial/team/update/{id}
    controller: App\Controller\TestimonialTeamController::updateTeamTestimonial
    methods: [PUT,PATCH]
team_testimonial_delete:
    path: /testimonial/team/delete/{id}
    controller: App\Controller\TestimonialTeamController::deleteById
    methods: DELETE       

#Services
get_all_services:
    path: /services/
    controller: App\Controller\ServicesController::getServices
    methods: GET
get_all_services2:
    path: /services/all
    controller: App\Controller\ServicesController::getAllServices
    methods: GET
get_services_with_content:
    path: /services/withContent
    controller: App\Controller\ServicesController::getServicesWithContent
    methods: GET
get_services_with_content_logo:
    path: /services/withContent2
    controller: App\Controller\ServicesController::getServicesWithContent2
    methods: GET
get_one_service:
    path: /services/{id}
    controller: App\Controller\ServicesController::getServiceById
    methods: GET
add_new_service_to_list:
    path: /services/create
    controller: App\Controller\ServicesController::addServiceToList
    methods: POST
count_service_list:
    path: /services/CountList/{isMother}/{id}
    controller: App\Controller\ServicesController::getListLength
    methods: GET
update_service:
    path: /services/update
    controller: App\Controller\ServicesController::updateService
    methods: [PUT,PATCH]
delete_service:
    path: /services/{id}
    controller: App\Controller\ServicesController::deleteService
    methods: DELETE 

#Service Content
get_content:
    path: /services/content/{id}
    controller: App\Controller\ServicesContentController::getContent
    methods: GET
add_content_to_service:
    path: /services/content/create
    controller: App\Controller\ServicesContentController::createContent
    methods: POST
update_content:
    path: /services/content/update/{id}
    controller: App\Controller\ServicesContentController::updateContent
    methods: [PUT,PATCH]
delete_content_by_service_id:
    path: /services/content/{id}
    controller: App\Controller\ServicesContentController::deleteContent
    methods: DELETE

#About Us
get_about_us_stram:
    path: /about/
    controller: App\Controller\AboutController::getAboutStram
    methods: GET
update_about_us_stram:
    path: /about/update
    controller: App\Controller\AboutController::updateAboutStram
    methods: [PUT,PATCH]
#About us team section
get_about_us_team:
    path: /about/team
    controller: App\Controller\AboutController::getTeam
    methods: GET
get_team_by_id:
    path: /about/team/{id}
    controller: App\Controller\AboutController::getTeamById
    methods: GET
create_team:
    path: /about/team/create
    controller: App\Controller\AboutController::createTeam
    methods: POST
update_team:
    path: /about/team/update/{id}
    controller: App\Controller\AboutController::updateTeam
    methods: [PUT,PATCH]
delete_team:
    path: /about/team/delete/{id}
    controller: App\Controller\AboutController::deleteTeamById
    methods: DELETE

#Partner Section
get_about_us_Partner:
    path: /partner
    controller: App\Controller\PartnerController::getPartner
    methods: GET
get_Partner_by_id:
    path: /partner/{id}
    controller: App\Controller\PartnerController::getPartnerById
    methods: GET
create_Partner:
    path: /partner/create
    controller: App\Controller\PartnerController::createPartner
    methods: POST
update_Partner:
    path: /partner/update/{id}
    controller: App\Controller\PartnerController::updatePartner
    methods: [PUT,PATCH]
delete_Partner:
    path: /partner/delete/{id}
    controller: App\Controller\PartnerController::deletePartnerById
    methods: DELETE

#clients 
clients:
    path: /client
    controller: App\Controller\ClientsController::index
    methods: GET

get_client_by_id:
    path: /client/{id}
    controller: App\Controller\ClientsController::getOne
    methods: GET

create_client:
    path: /client/create
    controller: App\Controller\ClientsController::addClient
    methods: POST

update_client:
    path: /client/update/{id}
    controller: App\Controller\ClientsController::updateClient

delete_client:
    path: /client/delete/{id}
    controller: App\Controller\ClientsController::deleteClient
    methods: DELETE
#newslette
get_all_newsletter:
    path: /newsletter
    controller: App\Controller\ContactController::list
    methods: GET
create_newsletter:
    path: /newsletter/create
    controller: App\Controller\ContactController::createNewsletter
    methods: POST
delete_newsletter:
    path: /newsletter/delete/{id}
    controller: App\Controller\ContactController::deleteNewsLetter
    methods: DELETE
#contact
get_all_contact:
    path: /contact
    controller:  App\Controller\ContactController::listContacts
    methods: GET
get_one_contact: 
    path: /contact/{id}
    controller: App\Controller\ContactController::readContact
    methods: GET
create_contact:
    path: /contact/create
    controller: App\Controller\ContactController::createContact
    methods: POST
delete_contact:
    path: /contact/delete/{id}
    controller: App\Controller\ContactController::deleteContact
    methods: DELETE

#spontanious applications
carriere_get_all_spontanious:
    path: /carrier/spontanious
    controller: App\Controller\CarriereController::getAllSpontanious
    methods: [GET]
create_spontanious_candidate:
    path: /carrier/spontanious/create
    controller: App\Controller\CarriereController::createSpontaneousCareer
    methods: POST
delete_spontanious_candidate:
    path: /carrier/spontanious/delete/{id}
    controller: App\Controller\CarriereController::deleteSpontanious
    methods: DELETE

#jobOffers
get_all_jobs:
    path: /carrier/jobs
    controller: App\Controller\CarriereController::getAllJobOffers
    methods: GET
get_one_job: 
    path: /carrier/job/{id}
    controller: App\Controller\CarriereController::getOneJob
    methods: GET
create_job:
    path: /carrier/job/create
    controller: App\Controller\CarriereController::createJob
    methods: POST
update_job:
    path: /carrier/job/update/{id}
    controller: App\Controller\CarriereController::updateJob
    methods: [PUT,PATCH]
hide_job_offer:
    path: /carrier/job/hide/{id}
    controller: App\Controller\CarriereController::hideJob
    methods: [PUT,PATCH]

#Application by job offer
create_candidate_by_job_offer:
    path: /carrier/offer/create/{id}
    controller: App\Controller\CarriereController::createCandidateByJobOffer
    methods: [POST]
get_applications_by_job_offer:
    path: /carrier/applications/{id}
    controller: App\Controller\CarriereController::getApplicationsByJobOffer
    methods: [GET]

#countries managment
get_all_countires:
    path: /country
    controller: App\Controller\CountryController::list
    methods: GET
get_all_countries22:
    path: /country
    controller: App\Controller\CountryController::getAllJobOffers
    methods: GET
create_country:
    path: /country/create
    controller: App\Controller\CountryController::createCountry
    methods: POST
delete_pays:
    path: /country/delete/{id}
    controller: App\Controller\CountryController::deleteCountry
    methods: DELETE

#projects 
projects:
    path: /project/getAllOne
    controller: App\Controller\ProjetController::getAllOne
    methods: GET
get_one_project: 
    path: /project/{id}
    controller: App\Controller\ProjetController::getOneProject
    methods: GET
get_projects_by_country_name: 
    path: /projects/byCountryName
    controller: App\Controller\ProjetController::getProjectsByCountry
    methods: POST    
create_project:
    path: /project/create
    controller: App\Controller\ProjetController::createProject
    methods: POST
update_project:
    path: /project/update/{id}
    controller: App\Controller\ProjetController::updateProject
    methods: [PUT, PATCH]
update_images_projects:
    path: /project/update/images/{id}
    controller: App\Controller\ProjetController::updateImages
    methods: [PUT, PATCH,POST]
delete_project:
    path: /project/delete/{id}
    controller: App\Controller\ProjetController::deleteProject
    methods: DELETE

#Project-services
get_services_by_project:
    path: /project/getServices
    controller: App\Controller\ProjetController::getAllServicesByProjectId
    methods: POST
add_service_to_project:
    path: /project/addService
    controller: App\Controller\ProjetController::addServiceToProject
    methods: POST
delete_service_from_project:
    path: /project/{projectId}/removeService/{serviceId}
    controller: App\Controller\ProjetController::removeServiceFromProject
    methods: DELETE

#similar-Project
get_similar_projects_by_project:
    path: /project/getSimilarProject
    controller: App\Controller\ProjetController::getAllSimilarProjectsByProjectId
    methods: POST
add_similar_project_to_project:
    path: /project/addSimilarProject
    controller: App\Controller\ProjetController::addSimilarProjectToProject
    methods: POST
delete_similar_project_from_project:
    path: /project/{projectId}/removeSimilarProject/{similarProjectId}
    controller: App\Controller\ProjetController::removeSimilarProjectFromProject
    methods: DELETE


#popular Projects
make_project_popular:
    path: /project/popular
    controller: App\Controller\ProjetController::makeProjectPopular
    methods: POST
make_project_non_popular:
    path: /project/unpopular
    controller: App\Controller\ProjetController::makePopularProjectNotPopular
    methods: POST
get_all_popular_project:
    path: /project/all/popular
    controller: App\Controller\ProjetController::getAllPopularProjects
    methods: GET

#authentification
login:
    path: /api/login
    controller: App\Controller\LoginController::login
    methods: ['POST']

register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: ['POST']
