app_back:
    path: /admin
    controller: App\Controller\BackController::index

app_front:
    path: /
    controller: App\Controller\FrontController::index

#HomePage
home_one_get:
    path: /home
    controller: App\Controller\AcceuilController::getHomeOne
    methods: GET

home_one_update:
    path: /home/homeOne/update
    controller: App\Controller\AcceuilController::updateHomeOne
    methods: [PUT,PATCH]

home_two_get:
    path: /home/homeTwo
    controller: App\Controller\AcceuilController::getHomeTwo
    methods: GET

home_two_update:
    path: /home/homeTwo/update
    controller: App\Controller\AcceuilController::updateHomeTwo
    methods: [PUT,PATCH]

#Testimonial
client_testimonial_get:
    path: /testimonial/client
    controller: App\Controller\TestimonialController::getAll
    methods: GET
client_testimonial_get_by_id:
    path: /testimonial/client/{id}
    controller: App\Controller\TestimonialController::getTestimonialById
    methods: GET
create_testimonial_client:
    path: /testimonial/client/create
    controller: App\Controller\TestimonialController::createClientTestimonial
    methods: POST
update_testimonial_client:
    path: /testimonial/client/update/{id}
    controller: App\Controller\TestimonialController::updateTestimonial
    methods: [PUT,PATCH]
client_testimonial_delete:
    path: /testimonial/client/delete/{id}
    controller: App\Controller\TestimonialController::deleteById
    methods: DELETE 
#Team Testimonial
team_testimonial_get:
    path: /testimonial/team
    controller: App\Controller\TestimonialTeamController::getAll
    methods: GET
team_testimonial_get_by_id:
    path: /testimonial/team/{id}
    controller: App\Controller\TestimonialTeamController::getTeamTestimonialById
    methods: GET
create_testimonial_team:
    path: /testimonial/team/create
    controller: App\Controller\TestimonialTeamController::createTeamTestimonial
    methods: POST
update_testimonial_team:
    path: /testimonial/team/update/{id}
    controller: App\Controller\TestimonialTeamController::updateTeamTestimonial
    methods: [PUT,PATCH]
team_testimonial_delete:
    path: /testimonial/team/delete/{id}
    controller: App\Controller\TestimonialTeamController::deleteById
    methods: DELETE       

#Services
get_all_services:
    path: /services/
    controller: App\Controller\ServicesController::getServices
    methods: GET
get_all_services2:
    path: /services/all
    controller: App\Controller\ServicesController::getAllServices
    methods: GET
get_services_with_content:
    path: /services/withContent
    controller: App\Controller\ServicesController::getServicesWithContent
    methods: GET
get_services_with_content_logo:
    path: /services/withContent2
    controller: App\Controller\ServicesController::getServicesWithContent2
    methods: GET
get_one_service:
    path: /services/{id}
    controller: App\Controller\ServicesController::getServiceById
    methods: GET
add_new_service_to_list:
    path: /services/create
    controller: App\Controller\ServicesController::addServiceToList
    methods: POST
count_service_list:
    path: /services/CountList/{isMother}/{id}
    controller: App\Controller\ServicesController::getListLength
    methods: GET
update_service:
    path: /services/update
    controller: App\Controller\ServicesController::updateService
    methods: [PUT,PATCH]
delete_service:
    path: /services/{id}
    controller: App\Controller\ServicesController::deleteService
    methods: DELETE 

#Service Content
get_content:
    path: /services/content/{id}
    controller: App\Controller\ServicesContentController::getContent
    methods: GET
add_content_to_service:
    path: /services/content/create
    controller: App\Controller\ServicesContentController::createContent
    methods: POST
update_content:
    path: /services/content/update/{id}
    controller: App\Controller\ServicesContentController::updateContent
    methods: [PUT,PATCH]
delete_content_by_service_id:
    path: /services/content/{id}
    controller: App\Controller\ServicesContentController::deleteContent
    methods: DELETE

#About Us
get_about_us_stram:
    path: /about/
    controller: App\Controller\AboutController::getAboutStram
    methods: GET
update_about_us_stram:
    path: /about/update
    controller: App\Controller\AboutController::updateAboutStram
    methods: [PUT,PATCH]
#About us team section
get_about_us_team:
    path: /about/team
    controller: App\Controller\AboutController::getTeam
    methods: GET
get_team_by_id:
    path: /about/team/{id}
    controller: App\Controller\AboutController::getTeamById
    methods: GET
create_team:
    path: /about/team/create
    controller: App\Controller\AboutController::createTeam
    methods: POST
update_team:
    path: /about/team/update/{id}
    controller: App\Controller\AboutController::updateTeam
    methods: [PUT,PATCH]
delete_team:
    path: /about/team/delete/{id}
    controller: App\Controller\AboutController::deleteTeamById
    methods: DELETE



#contact
app_contact:
    path: /contact
    controller: App\Controller\ContactController::index

app_contact_algerie:
    path: /algerie
    controller: App\Controller\ContactController::algerie

app_contact_senegal:
    path: /senegal
    controller: App\Controller\ContactController::senegal

app_contact_niger:
    path: /niger
    controller: App\Controller\ContactController::niger

app_contact_benin:
    path: /benin
    controller: App\Controller\ContactController::benin


#carriere
carriere_index:
    path: /carriere
    controller: App\Controller\CarriereController::index
    methods: [GET]

carriereAdmin:
    path: /carriereAdmin
    controller: App\Controller\CarriereController::carriereAdmin
    methods: [GET]

ajouterCarriere:
    path: /ajouterCarriere
    controller: App\Controller\CarriereController::ajouterCarriere
    methods: [GET, POST]

modifierCarriere:
    path: /modifierCarriere/{id}
    controller: App\Controller\CarriereController::modifierCarriere

suppressionCarriere:
    path: /suppressionCarriere/{id}
    controller: App\Controller\CarriereController::suppressionCarriere







carriere_submit:
    path: /candidature/submit
    controller: App\Controller\CarriereController::submit
    methods: [POST]

offres : 
    path: /offres
    controller: App\Controller\OffresController::index
    methods: [GET]


#clients 
clients:
    path: /clients
    controller: App\Controller\ClientsController::index

clients_admin:
    path: /clientsAdmin
    controller: App\Controller\ClientsController::clientsAdmin
    methods: [GET]

ajouterClient:
    path: /ajouterClient
    controller: App\Controller\ClientsController::ajouterClient
    methods: [GET, POST]


modifierClient:
    path: /modifierClient/{id}
    controller: App\Controller\ClientsController::modifierClient

suppressionClient:
    path: /suppressionClient/{id}
    controller: App\Controller\ClientsController::suppressionClient



#métiers
metiers:
    path: /metiers
    controller: App\Controller\MetierController::index

ajouterMetier:
    path: /ajouterMetier
    controller: App\Controller\MetierController::ajouterMetier
    methods: [GET, POST]


modifierMetier:
    path: /modifierMetier/{id}
    controller: App\Controller\MetierController::modifierMetier

suppressionMetier:
    path: /suppressionMetier/{id}
    controller: App\Controller\MetierController::suppressionMetier


#projets 
projets:
    path: /projets
    controller: App\Controller\ProjetController::index

ajouterProjet:
    path: /ajouterProjet
    controller: App\Controller\ProjetController::ajouterProjet
    methods: [GET, POST]


modifierProjet:
    path: /modifierProjet/{id}
    controller: App\Controller\ProjetController::modifierProjet

suppressionProjet:
    path: /suppressionProjet/{id}
    controller: App\Controller\ProjetController::suppressionProjet


#affichage



stram:
    path: /gestionStram
    controller: App\Controller\StramController::gestionStram


gestion_Contact:
    path: /gestionContact
    controller: App\Controller\GestionContactController::gestionContact


# Route pour afficher la page de gestion des contacts
gestion_contact:
    path: /gestionContact
    controller: App\Controller\GestionContactController::gestionContact
    methods: ['GET']


# Route pour modifier les coordonnées de la Tunisie
modifier_contact_tunisie:
    path: /modifierContactTunisie
    controller: App\Controller\GestionContactController::modifierContactTunisie
    methods: ['GET', 'POST']

# Route pour supprimer les coordonnées de la Tunisie
supprimer_contact_tunisie:
    path: /supprimerContactTunisie
    controller: App\Controller\GestionContactController::supprimerContactTunisie
    methods: ['GET']


# Route pour modifier les coordonnées de l'Algerie
modifier_contact_algerie:
    path: /modifierContactAlgerie
    controller: App\Controller\GestionContactController::modifierContactAlgerie
    methods: ['GET', 'POST']

# Route pour supprimer les coordonnées de l'Algerie
supprimer_contact_algerie:
    path: /supprimerContactAlgerie
    controller: App\Controller\GestionContactController::supprimerContactAlgerie
    methods: ['GET']



#---------------------------------------------

reparation:
    path: /reparation
    controller: App\Controller\RéparationController::index
    methods: ['GET']


RenforcementChemisageClassique:
    path: /renforcement/chemisage/classique
    controller: App\Controller\RenforcementChemisageClassiqueController::index
    methods: ['GET']


renforcementFibreCarbone:
    path: /renforcement/fibre/carbone
    controller: App\Controller\RenforcementFibreCarboneController::index
    methods: ['GET']

#---------------------------------------------

Étanchéité:
    path: /Étanchéité
    controller: App\Controller\ÉtanchéitéController::index
    methods: ['GET']

Imperméabilisation:
    path: /Imperméabilisation
    controller: App\Controller\ImperméabilisationController::index
    methods: ['GET']

#---------------------------------------------
traitement/traitement/jointsJoints:
    path: /traitement/joints
    controller: App\Controller\TraitementJointsController::index
    methods: ['GET']

#---------------------------------------------
RevêtementTechnique:
    path: /RevêtementTechnique
    controller: App\Controller\RevêtementTechniqueController::index
    methods: ['GET']

TraitementFaçades:
    path: /TraitementFaçades
    controller: App\Controller\TraitementFaçadesController::index
    methods: ['GET']


#authentification
login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: ['GET']

register:
    path: /register
    controller: App\Controller\RegisterController::register
    methods: ['GET']
