<?php

namespace ContainerKs0f6uy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0VaziksService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0Vaziks' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0Vaziks'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'projet' => ['privates', '.errored..service_locator.0Vaziks.App\\Entity\\Projet', NULL, 'Cannot autowire service ".service_locator.0Vaziks": it references class "App\\Entity\\Projet" but no such service exists.'],
        ], [
            'projet' => 'App\\Entity\\Projet',
        ]);
    }
}
