<?php

namespace ContainerKs0f6uy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FPvaKaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fPva_Ka' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fPva_Ka'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'metier' => ['privates', '.errored..service_locator.fPva_Ka.App\\Entity\\Metier', NULL, 'Cannot autowire service ".service_locator.fPva_Ka": it references class "App\\Entity\\Metier" but no such service exists.'],
        ], [
            'metier' => 'App\\Entity\\Metier',
        ]);
    }
}
