<?php

namespace ContainerKs0f6uy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fPva_Ka.App\Entity\Metier' shared service.
     *
     * @return \App\Entity\Metier
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.fPva_Ka": it references class "App\\Entity\\Metier" but no such service exists.');
    }
}
