<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerROQFWR2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerROQFWR2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerROQFWR2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerROQFWR2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerROQFWR2\App_KernelDevDebugContainer([
    'container.build_hash' => 'ROQFWR2',
    'container.build_id' => '1878c57a',
    'container.build_time' => 1694595471,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerROQFWR2');
