<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPwxfYXB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPwxfYXB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPwxfYXB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPwxfYXB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPwxfYXB\App_KernelDevDebugContainer([
    'container.build_hash' => 'PwxfYXB',
    'container.build_id' => 'aa0f231a',
    'container.build_time' => 1694895667,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPwxfYXB');
